FRONT-END-BOOTCAMP-PLUS-4/MoCha

app/(auth)/find-id/page.tsx

**변경 내용 요약**
- 아이디 찾기 페이지 UI 생성했습니다.
- 에러 메세지까지 포함하여 생성했습니다.
**변경 유형**
어떤 변경 사항이 있나요?

아이디 찾기 페이지 UI 생성

---

app/(auth)/find-id/page.tsx
app/(auth)/login/page.tsx
app/(auth)/signup/page.tsx
app/components/auth/ErrorMessage.tsx
app/components/auth/LogoImage.tsx
app/components/auth/Title.tsx

**변경 내용 요약**
- 로그인 페이지 에러 메세지 추가
- 회원가입 페이지 에러 메세지 추가
- auth에서 사용하는 Title, LogoImage, ErrorMessage 컴포넌트 생성
- 로그인 페이지 회원가입, 아이디 찾기, 비밀번호 찾기 버튼 -> 링크로 변경
**변경 유형**
어떤 변경 사항이 있나요?

로그인, 회원가입 페이지 에러 메세지 추가

---

app/(auth)/find-id/page.tsx
app/(auth)/find-password/page.tsx

**변경 내용 요약**
- 비밀번호 찾기 페이지 UI 생성했습니다.
- 아이디 찾기 에러 메세지 컴포넌트 적용했습니다.
**변경 유형**
어떤 변경 사항이 있나요?

비밀번호 찾기 페이지 UI 생성

---

app/(auth)/social-info/page.tsx

**변경 내용 요약**
- 추가 정보 입력 페이지 UI 생성했습니다.
**변경 유형**
어떤 변경 사항이 있나요?

추가 정보 입력 페이지 UI 생성

---

app/(core)/page.tsx
app/components/main/FloatingButton.tsx
app/components/main/FullCalendarWrapper.tsx
app/components/main/SummaryHeader.tsx
app/types/Calendar.ts
package-lock.json
package.json

**변경 내용 요약**
- 메인 페이지에 캘린더, total 값, 내역 추가 버튼 구현
**변경 유형**
어떤 변경 사항이 있나요?

메인 페이지 UI 구성

---

app/(core)/page.tsx
app/components/main/modal/IncomeExpenseForm.tsx
app/components/main/modal/TransactionModal.tsx
app/globals.css
app/shared/types/Calendar.ts

**변경 내용 요약**
- 수입/지출 입력 모달 제작
**변경 유형**
어떤 변경 사항이 있나요?

수입/지출 입력 모달 제작

---

app/(core)/layout.tsx
app/(core)/user/page.tsx
app/components/user/CategoryChart.tsx
app/components/user/CategoryList.tsx
app/components/user/PeriodBarChart.tsx
app/globals.css
app/shared/types/Chart.ts

**변경 내용 요약**
- barChart 생성
**변경 유형**
어떤 변경 사항이 있나요?

BarChart생성

---

app/(auth)/find-id/page.tsx
app/(auth)/find-password/page.tsx
app/(auth)/layout.tsx
app/(auth)/login/page.tsx
app/(auth)/signup/page.tsx
app/components/auth/Title.tsx
app/shared/ui/button/Button.tsx
app/shared/ui/input/Input.tsx
app/shared/ui/label/Label.tsx

**변경 내용 요약**
- 공통 컴포넌트의 css 일부 수정했습니다.
- auth 페이지의 css 수정했습니다.
**변경 유형**
어떤 변경 사항이 있나요?

Auth 페이지 css 수정

---

app/components/main/FullCalendarWrapper.tsx
app/shared/utils/formattedDate.ts

**변경 내용 요약**
- 날짜 formatted 함수 분리
**변경 유형**
어떤 변경 사항이 있나요?

refactor: 날짜 formatted 함수 분리

---

app/api/category/route.ts
app/components/user/container/CategoryContainer.tsx
application/usecases/category/GETmonthlyCategoryUsecase.ts
domain/entities/Transaction.ts
domain/repositories/CategoryRepo.ts
domain/repositories/TransactionRepo.ts
infra/repositories/supabase/SbCategoryRepo.ts

**변경 내용 요약**
- Category API 생성
- 
**변경 유형**
어떤 변경 사항이 있나요?

feat: Category API 생성

---

app/(auth)/signup/page.tsx
app/api/transactions/monthly/route.ts
application/usecases/auth/LoginUseCase.ts
domain/entities/User.ts
infra/repositories/supabase/SbTransactionRepo.ts
infra/utils/jwt.ts

**변경 내용 요약**
- user id 삭제한거 롤백
**변경 유형**
어떤 변경 사항이 있나요?

feat: User entity 수정

---

app/(auth)/signup/page.tsx
app/api/transactions/daily/route.ts
app/api/transactions/monthly/route.ts
application/usecases/auth/LoginUseCase.ts
domain/entities/User.ts
infra/repositories/supabase/SbTransactionRepo.ts
infra/utils/jwt.ts

**변경 내용 요약**
- daily, monthly route 수정(user.id로 판단 안되는 부분)
**변경 유형**
어떤 변경 사항이 있나요?

feat: daily, monthly route 수정

---

app/(auth)/find-id/page.tsx
app/(auth)/layout.tsx
app/(auth)/login/page.tsx
app/(auth)/reset-password/page.tsx
app/(auth)/signup/page.tsx
app/api/auth/send-code/reset-password/route.ts
app/components/auth/AuthProvider.tsx
app/components/auth/GoogleLoginButton.tsx
app/components/auth/KakaoLoginButton.tsx
app/layout.tsx
app/shared/ui/button/index.tsx
app/shared/ui/input/PasswordInput.tsx
app/shared/ui/input/index.tsx
application/usecases/user/GetUserUseCase.ts
application/usecases/user/dto/UserProfileDto.ts

**변경 내용 요약**
- 이메일 인증번호 버튼 클릭 시, 전송중 & 스피너 표시
- 로그인 상태일 경우, 로그인/회원가입 페이지 접근 차단("/"으로 push)
- User 정보 반환 값 수정
**변경 유형**
어떤 변경 사항이 있나요?

feat: 버튼 로딩 적용, 로그인 시, 로그인/회원가입 페이지 접근 차단

---

app/(auth)/kakao-callback/page.tsx
app/(auth)/login/page.tsx
app/api/auth/google/route.ts
app/api/auth/kakao/exchange/route.ts
app/api/auth/login/route.ts
app/api/auth/refresh/route.ts
app/components/auth/AuthProvider.tsx
app/components/auth/GoogleLoginButton.tsx
app/shared/utils/refreshToken.ts
application/usecases/auth/GoogleLoginUseCase.ts
application/usecases/auth/KakaoLoginUseCase.ts
application/usecases/auth/LoginUseCase.ts
application/usecases/user/SignupUsecase.ts
infra/oauth/KakaoOAuthService.ts
infra/repositories/supabase/SbUserRepo.ts
infra/utils/jwt.ts

**변경 내용 요약**
- refresh_token 생성
- refresh_token으로 만료된 access_token 재발급
- 일반/구글/카카오 로그인 refresh_token 적용
- 콘솔 제거
**변경 유형**
어떤 변경 사항이 있나요?

feat: refresh_token으로 만료된 access_token 재발급

---

app/(core)/page.tsx

**변경 내용 요약**
- 데이터 바인딩 수정
- token 없을 시 api fetch skip
**변경 유형**
어떤 변경 사항이 있나요?

Refactor: api fetch 방식 수정

---

app/(core)/page.tsx
app/api/category/route.ts
app/api/transactions/route.ts
app/components/main/FullCalendarWrapper.tsx
app/components/main/modal/IncomeExpenseForm.tsx
application/usecases/category/GETcategoryUsecase.ts
application/usecases/category/dto/CategoryDto.ts
application/usecases/transactions/PostTransactionUsecase.ts
application/usecases/transactions/dto/TransactionsDto.ts
domain/repositories/CategoryRepo.ts
domain/repositories/TransactionRepo.ts
infra/repositories/supabase/SbCategoryRepo.ts
infra/repositories/supabase/SbTransactionRepo.ts

**변경 내용 요약**
- 카테고리 목록 조회 api 구현 및 연결, 항목 추가 api 구현 및 연결
**변경 유형**
어떤 변경 사항이 있나요?

feat: 항목 추가 기능 구현

---

app/api/user/edit/route.ts
app/api/user/password/route.ts
app/components/user/container/PasswordChangeContainer.tsx
app/components/user/container/PasswordContainer.tsx
app/components/user/presentation/PasswordChange.tsx
app/components/user/presentation/PasswordCheck.tsx
application/usecases/user/ChangePasswordUsecase.ts
application/usecases/user/MatchPasswordUsecase.ts

**변경 내용 요약**
- 비밀번호 변경 API 생성
**변경 유형**
어떤 변경 사항이 있나요?

비밀번호 변경 API 생성

---

app/api/transactions/route.ts
app/components/main/FullCalendarWrapper.tsx
app/components/main/modal/DailyDetailModal.tsx
app/components/main/modal/TransactionItem.tsx
application/usecases/transactions/DeleteTransactionUsecase.ts
domain/repositories/TransactionRepo.ts
infra/repositories/supabase/SbTransactionRepo.ts

**변경 내용 요약**
- 항목 삭제 api 구현 및 연결
**변경 유형**
어떤 변경 사항이 있나요?

feat: 항목 삭제 기능 구현

---

app/(core)/page.tsx
app/components/main/FullCalendarWrapper.tsx
app/shared/ui/root-header/ui/ButtonList.tsx

**변경 내용 요약**
- 데이터 등록 시, 새로고침 없이 데이터 패칭
- 상세내역 모달의 데이터 삭제 시, 새로고침 없이 데이터 패칭
- 로그아웃 시, 로그인 페이지로 이동
**변경 유형**
어떤 변경 사항이 있나요?

feat: 데이터 패칭 로직 수정

---

app/(core)/user/page.tsx

**변경 내용 요약**
- ex) 로그인 시, 네이버 소셜 로그인 기능을 추가했습니다.
**변경 유형**
어떤 변경 사항이 있나요?

Feat: userPage 경로처리
